project:
  name: "TXTDirect"
  state: "beta"
  image: "https://raw.githubusercontent.com/txtdirect/txtdirect/master/media/logo.svg?sanitize=true"
  website: "https://about.txtdirect.org"
  oneLiner: "Convenient redirects based on DNS TXT-records"
  description: |
    Convenient and minimalistic DNS based redirects, while controlling your data with your own DNS records.
  version: "v0.4.0"

vision:
  type: "community"
  overview: |
    TXTDirect thrives to give back control and data to redirects.
  concept: "Instead of relying on external providers to control redirect data. TXTDirect uses data stored within your own DNS records and provides an easily switchable backend service/implementation."
  aim: "TXTDirect provides the specification for redirection records and a based implementation as caddy plugin."

supportLinks:
  documentation: "https://txtdirect.org/docs"

contributionLinks:
  issueTemplate: "/.github/ISSUE_TEMPLATE.md"
  starterIssues: "https://github.com/txtdirect/txtdirect/labels/starter%20issue"

emails:
  commercialSupport: "support@okkur.org"
  security: "security@okkur.org"
  coc: "coc@okkur.org"

copyright:
  year: "2017"

cla:
  copyrightHolder: "nzt.ventures GmbH"
  mail: "legal@nzt.ventures"

maintainers:
  - name: "Michael Grosser"
    nick: "stp-ip"
  - name: "Erfan Besharat"
    nick: "erbesharat"

repo:
  link: "https://txtdirect.org/code/"
  type: "Github"

issueTemplate:
  questions:
  - "OS"
  - "Caddy version"

badges:
  - image: "https://img.shields.io/badge/state-beta-blue.svg"
    alt: "state"
  - image: "https://img.shields.io/github/release/txtdirect/txtdirect.svg"
    link: "https://txtdirect.org/releases/"
    alt: "release"
  - image: "https://img.shields.io/github/license/txtdirect/txtdirect.svg"
    link: "https://txtdirect.org/license/"
    alt: "license"
  - image: "https://travis-ci.org/txtdirect/txtdirect.svg?branch=master"
    alt: "Build Status"
    link: "https://travis-ci.org/txtdirect/txtdirect"

reposeed:
  configVersion: "v1"
