name: CI

on: 
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Automatically create documentation issues
      uses: okkur/actions-godocit@v0.0.1
      with:
        targetRepo: 'txtdirect/website'
      env:
        PRIVATE_KEY: ${{ secrets.PrivateKey }}
        INSTALLATION_ID: ${{ secrets.InstallationID }}
